---
- hosts: "api01"
  remote_user: ubuntu
  become: true
  tasks:

  - name: Copy the api01.yml
    copy:
      src: "/var/lib/jenkins/workspace/cp-api01/deployment/docker-compose/api01/api01.yml"
      dest: /root
      mode: 0755

  - name: Copy the api01.sh
    copy:
      src: "/var/lib/jenkins/workspace/cp-api01/deployment/docker-compose/sh/api01.sh"
      dest: /root
      mode: 0755

  - name: pull api01 image
    shell: "/bin/bash /root/api01.sh"

  - name: up api01 image
    command: "docker-compose -f /root/api01.yml up -d"
